= Kiali Test Mesh
:toc: macro
:toc-title:

toc::[]

== Introduction

Kiali test components to be used to generate test service meshes to validate that our components are functioning as expected.

Currently this project will just build a simple web server, 'Kiali Test Service', which allows for easy routing between other similar test services with a REST call. This allow someone to create arbitary service mesh topologies just by varying the URLs being used. This is useful for testing purposes and making sure that the service graph can properly render different types of service meshes.

A few example service mesh topologies can also be generated during the build using the `make openshift-deploy'.

=== Kiali Test Service

The 'Kiali Test Service' is a simple Go based server which will allow easy routing between nodes in your service graph using only a single REST call.

The main endpoint of interest is the '/route' endpoint which can be passed a 'path' query parameter containing a comma delimited list of nodes to be visited.

For example, consider you are running a cluster of 3 'Kiali Test Services' where they have hostnames of 'a', 'b' and 'c'. The following URL will cause the 'a' service to connect to 'b' which then cause 'b' to connect to 'c': 'http://a/route?path=b,c'. Using similar endpoints can be used to quickly generate any type of service graph topology.

=== License and Copyright

See the link:./LICENSE[LICENSE file].

== Building

=== Building the Kiali Test Service

[NOTE]
In order to build the 'Kiali Test Service' you will need to have make and Go lang installed and available on your $PATH.

To build the 'Kiali Test Service' you will need to clone the project from git into your 'GOPATH' and run the 'make' command.

For example, to check 'kiali-test-mesh' into your home directory under a directory called 'kiali-test-mesh':

[source,shell]
----
export GOPATH=$HOME/kiali-test-mesh
mkdir -p $GOPATH
cd $GOPATH
mkdir -p src/github.com/kiali
cd src/github/kiali
git clone https://github.com/kiali/kiali-test-mesh
cd kiali-test-mesh
make build
----

=== Building the Kiali Test Service

[NOTE]
In order to build the 'Kiali Test Service' docker image, you will need to have docker installed, available on your path and run the command as a user who has permission to build docker images

To build the 'Kiali Test Service' docker image you will need to just run the 'docker-build' make command.

[source,shell]
----
make docker-build
----