id: kiali-test-service
kind: Template
apiVersion: v1
name: Kiali Test Service Template
description: Deploys a service for the test mesh
parameters:
- name: SERVICE_NAME
  description: The name to use for the service
  required: true

- name: POD_NAME_LABEL
  description: The name label used on all the pods in the service
  required: true

objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${SERVICE_NAME}
  spec:
    selector:
      name : ${POD_NAME_LABEL}
    ports:
    - name: http
      port: 80
      targetPort: 8888
