sudo: required
services:
- docker
language: go
go:
- 1.9.4
notifications:
  irc:
    channels:
    - chat.freenode.net.#kiali
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
env:

  global:
  - secure: "dG462YKOrUnTSQ3pKnSCQiZywAutbmGeIVucjrkbiz3RCfYQrNUwTfsOI3EeTN8VdmyD6RoV0yH0N4UI6mok22gpgEPjRLSI+eRC/W2+8bbQ3dsdb/4qIFpEh1QC5mv+l1/ZrJs+FH32h40RlPnuxccisn3djlV5IgSie5CbDb3MjIy/3uXnX7kNdEMadh3ST+0TnZP6fjofl15+DFckpqUt+ijOoUZXjQF+PZR7xWh4mpHwR1JMUF7wZX4dqvyr2RcQ/of9ZClmyey8+zHHkaKxIEeTV+O4IRKxlchuSTjsUhpXHqDIHRVrgeai4T4Q7x9l6yp3up4nEYZg8AZl7XgqJNk6uY9rqv4QKP/2dpsasBu5vVTWQ7X32UfT0q+MfZqg+nIE7zzWoo7JaY1DNWphgka/ApxE0cTxll74B7dJ/EIpo87rqRzyrCFG/IamY0Mc0TO5n85wh5YSn0tMX58KiTBvpLvAuk+B9s6BIxH6KuCc7lx+F7LbRaLdJxmwnvSjuIESOjiaHGg/GmoIUZ98b9LL2w4tSVOEAGVZsu0mUhhBPtlzYMyKMMUhomGNs7f2HxD58oC+vnP9vJKy6q7YBr/FDSuHpozoMUe9pBDVJcXIMbWNf8tnhaCXH35NjT9opwcCpB6VisZt4zZbfHNUXC/26P6F+cMnLbgmyO4="
  - secure: "F1uK9G9OJgd2ktsJWJT3KrY70k0a29Ha6DevdEhRAKJV9DiAxuYy9oKEgKRKgU9VtmcdPA1nq+T7hxhNGjWa2UbaIZsd1wHR8YH9SaJ7h/I2M05OXsb0FGndW4qCTfMGliZi5kjiULGP+1KpVWy5Tpd1FoLHqUjEq7zQC/nRnC4BmDbqtCouIzepFvN42ie2MUIoAN7blxQB91eYC0RNe4RsS4Q7bGY8E0w2q40eSnPlfZiDjlngLLdiF/ilnIzEPz0JOjNW9sAu/RwKZuhw5kOESFM1608Zof9j5XCnRC3B0bdVN1c57f8RU7w+Hpk1JCAy86yg+uKgFhIismdksrsfzbWQ1QHb/hFpkAcWDowOjowrOZT/d9xVpNDg9re6pKW/cQBb5/yPnCiejhtbf3Q7QNoMpfodBDMcHDACe9o/tYyOiE/L61RojRBjZoORmKy4NuQsVpYxOtPbzQGqEncaC9SGEuoNkadl92+YGvJNObDSSzuhDeQGvvRpj7xQqupVWHr5kaEJnP+dY+oA1RafhuyjCrlqU/1Mjg48owG6z/w7NpiBhuesDcJjBI7fMzq03RNfdvEkmjMIJ2aTIA7WOTZ8yvIKFqWLdselTZFKVcaK/uT8ntoFqoh1u0XPZra7HpNYPn5W2I6Uh2HClYz3lzaDWMkg8S/n/Zae8zI="

script:
  - export GOPATH=$HOME/kiali-test-mesh; mkdir -p $GOPATH; cd $GOPATH; mkdir -p src/github.com/kiali; cd src/github.com/kiali; git clone https://github.com/kiali/kiali-test-mesh; cd kiali-test-mesh; make all

  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker push kiali/kiali-test-service
  - docker push kiali/kiali-test-mesh-traffic-generator

branches:
  only:
  - master
  - /^(\d+\.){2}(\d+){1}(\.[a-zA-Z\d]+)?$/
