sudo: required
services:
- docker
language: go
go:
- 1.9.4
notifications:
  irc:
    channels:
    - chat.freenode.net.#kiali
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
env:

  global:
  - secure: "G3BjmuTu0Dbm0mV/Myb53gcvLFKXZ/qVXbfwSLHfWpQw/18PJaf1lJ/yVsywAm8C5ob3TLO5uEG0gqPG3RhE3kNY8Mj7Y3umDB7kFgYD1XiR2zNbETOds1fumNjiMLYhDVfIBjMqmAgEldHtrcvs0TZC3NUcS+bJmyQYHVltqVBzmJR7lQtovB7WRAsBD3DDj79DXeHgvcoHz5BZCRTxKduaxSQnuUqFcrLfSQ5vbU+C9RJ72HlNvl8nNXdVUER9F6VFbotgyyV/zjDDtLbvAI7S/3zBEt/h+0LqHI4MWfPy1vkN34DjAzXYcnRzbMaOQnRlWrqxujWdcCUdmVo2rOqdC/J2/js6sOC3sxBYiZbwcnHOkmst94PHOF/AY/g2WwGDqCClifP6FntnvDFKnvw01SRwqt+7WowrEtAUJXS5/Gwlz4daVtKwGx2ct7JCDFpwJLWkLXVHqg5c6sZwitmJjWRq5rDtWwV0zZnEIq6ygn0GWRSPbzyfEUpnXcCsybtBK7oYZDUZpz5myuS1lHCXRaTHwYInTFHlPKpyWSm84sDQV2QYZ5SxVplfb+Kk7oasyG0FE3xwHCWFfqScGShC6/MsvanFSt7LI5HCPF8vfbVqY9hhUqfpY5hlCEcfigsT2hqvxuYUd56C4rcCfE+FynyOp1bcY/UPudztWN4="
  - secure: "sNre0mmOAVT/XdTp4aVPiGil8p+gE3g/eQbjoXSuXubncNy9QL1DWiCCPuYdyxb0I0ajQohHsfjfEDHNQHIFv2IoGhphLzAbhNa2vnmMG7x6ULHoWXMQTp7wZCBmum2koCD8k9iHBEfsC+PTZzc0UeFQ32+A3jvW4uN1ZC186ze9wXhatEaEU53uCbVBkxYnYY1sv2fyigWCHJJT5rnhkQdzDYJUOgeT0+guH+l/oLsaO2zduaXU5dNCwCfLVTizi6qjeznR6Px5Pany08o3klGCyZ9Sq343pmi5lw59rFGgOJZXyIQ9DwIg0thpJXEcXGb3tA+2Sa4XKzT6hHT1M+rs38aW08x82BdgI89x5lZyQKSfbXC1IFkanNXvthYLsftVxuhsBMV3ttseFJwVZE36s/BjR+9XqP/4NGjwXGV4ZPnEyLeJ02Ouh/gkVZOsnHGcvf63hyLhG3FAjseXnzX8OZPwAMSL6kqSznJELComEFJJwcnHYJRUlcT2sw+9NbyWGSUIR8xE5z5FKjnI3qKkty9JorfrXmPBvl3bTjjg9LwDXPzpKheAldFJwFugPhPOLpQI+o7iekdWA5XTgTT+33GreaRrMLxL7FM9TvcMHVZTmvEa433We7hVOTnDIN0XOoQ+dxD/muxhKVIbWs258UUn8SIs/6ovUmLigds="

script:
  - export GOPATH=$HOME/kiali-test-mesh; mkdir -p $GOPATH; cd $GOPATH; mkdir -p src/github.com/kiali; cd src/github.com/kiali; git clone https://github.com/kiali/kiali-test-mesh; cd kiali-test-mesh; make all

  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker push kiali/kiali-test-service
  - docker push kiali/kiali-test-mesh-traffic-generator

branches:
  only:
  - master
  - /^(\d+\.){2}(\d+){1}(\.[a-zA-Z\d]+)?$/
