sudo: required
services:
- docker
language: go
go:
- 1.9.4
notifications:
  irc:
    channels:
    - chat.freenode.net.#kiali
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
env:

  global:
  - secure: "cHwEWC7R4tIWFV2bi+OeSbRFw7Qz4yQ4DOw12/TMV40zt0hkj+v4D36CvR5JfJxX6ICaLSpOjewmBRnM+WFwfrsapZW/X5iUP5kgT2bLrlZbcyvD/IwiNjwTVX+Via6xrw1RMZAP6AuLOskt8d6ZSqlFBpfAd4L6iY5D+xRZazKlVoHztDWh8u/454mygI1IwfUfAbDgIEBw1Q7Fe/x0sGLu2go1bhnUXv0r1rN4KGKth/vVNBdTUXHnZioVbgQMaf3BOOOmRoETOKod+WKEA7kkv4vrItbHLLKGu3gaQ2EUkqL0bTCrk690qWcN5331BjzBOCpOVThM0///Zj1gAj6p2OjsaANOybUL+bedw3cwyIKRXe/k51SuQ4+ac7gCC1Ix4w+QEoOgR5Xh9P1uArw4jj7XzrYrbi6GfpfUlh5xc6BQ8rupjL0aHHw0boGvty32BcTejyIg2vLj3eejvhaBzQYkg+RaO8O55LumRcicboDjmzDioxe6w2YyMkPGDRgQiOt0inQEIsx65DzoKSUGXTDLfqkMGa2/tHBtlZdddn3M+NIWM1NG2ONpnZXdFnj9fIitKlbQ7fN6vXGVI+5SheGIyoPXLTTqIV4eUCp7FpKoWSpPEpPYMpXrsqlkLcPvMjaRfZF0/k4Wwuj2VMFwNG7ahlYD3Q+gqbTW2S0="
  - secure: "iYfuqtJyT5+GbWzWAwS2gMhJGZctnDSn9ZDk2pjkPCwjoADKP/kHW7H4Sa219vxXcyl4w+4XKbdFl+rb8ylZgva4jugwrE2m1qG57hUDMOgy0abqWtfv5gxWMKsoFoWdRwDE8/RAGYWJpCc9kqNdEy2e2PMVBs+0//s+BublDUgyuj5fKsZLTaIB/2PhS4aQQi3+p1D1Nz6zRwe13h1eU/IuEyXWnoSEaJFzWD8hocTZ5gL4c41TrgjjcnvS14ozTjXbTlihSF6c/pFhFPNBPgNCWSsV9asfrYPQOKObdaF2frRykaI+VW+sZoGTu45fjjbUFpR1OidV7uFB+RsQ6Hb2nNSr61iViMswoacTRsoSv8Hp65NDaGgMXTbaf4AB8dHP7yNr14XtuLOuo0LszEawmdrWwkstTkTJvMqD+/yRv8ceid5cv6/TQCG+Kd/EdC+MfOm2cARZsowUZ2EvkfH3HWevW1+qRwnh6KK3yJ236MCW7fODaumRBRmmG97n08sTB9ikPqLQu+xlbxJLuDo+3YSzCv5GmpkbpF7ZdygOFPU65mA6PZyIUiXAQuIjLEsYZRRo0FBUfYyZTIMeoHgcCkAcvCIY/XMPBqPLxggLbydQOzCG/Vz2AlvpkSgyEouqyovNeP8uwF3yu0iIb9wuuKlKoVcVRQJSFm8AeTI="

script:
  - export GOPATH=$HOME/kiali-test-mesh; mkdir -p $GOPATH; cd $GOPATH; mkdir -p src/github.com/kiali; cd src/github.com/kiali; git clone https://github.com/kiali/kiali-test-mesh; cd kiali-test-mesh; make all

  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker push kiali/kiali-test-service
  - docker push kiali/kiali-test-mesh-traffic-generator

branches:
  only:
  - master
  - /^(\d+\.){2}(\d+){1}(\.[a-zA-Z\d]+)?$/
