= Kiali Test Mesh Operator

Kiali provides an operator which will install different types of examples mesh which allow you to see different features of kiali.

In order to Deploy the Operator you can use following make target (on root folder of this repository)

[source,shell]
----
make operator-deploy-openshift
----

or you can use the following commands to deploy on openshift


[source,shell]
----
oc new-project kiali-test-mesh-operator
oc create -f operator/kiali-test-mesh-operator/deploy/bookinfo-crd.yaml
oc create -f operator/kiali-test-mesh-operator/deploy/complex_mesh-crd.yaml
oc create -f operator/kiali-test-mesh-operator/deploy/service_account.yaml
oc create -f operator/kiali-test-mesh-operator/deploy/role_binding.yaml
oc create -f operator/kiali-test-mesh-operator/deploy/operator.yaml
----

for kubernetes use the following commands;

[source,shell]
----
kubectl create namespace kiali-test-mesh-operator
kubectl create -f operator/kiali-test-mesh-operator/deploy/bookinfo-crd.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/complex_mesh-crd.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/service_account.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/role_binding.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/operator.yaml
----

After installing the operator you can install the custom resource for each type of mesh that might want to try.

Meshes available:

- Bookinfo from Istio
- Kiali Complex Mesh


== Bookinfo from Istio 

=== Automatic Injection of Istio sidecar

After installing the <<Kiali Test Mesh Operator>>, you may install link:https://preliminary.istio.io/docs/examples/bookinfo/[Bookinfo] from Istio Sample  can be easily installed as part of the operator. You can choose to deploy with link:https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection[automatic injection of the sidecar] make target to deploy on openshift:

[source,shell]
----
make deploy-bookinfo-automatic-sidecar
----

or with the following command for openshift

[source,shell]
----
oc create -f operator/kiali-test-mesh-operator/deploy/cr/automatic-sidecar/bookinfo-cr.yaml
----

or with the following command for kubernetes

[source,shell]
----
kubectl create -f operator/kiali-test-mesh-operator/deploy/cr/automatic-sidecar/bookinfo-cr.yaml
----


=== Manual Injection of the Istio sidecar
In order to deploy with link:https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#manual-sidecar-injection[manual injection of sidecar] you can use the make target to deploy on openshift

[NOTE]
Check the version which of `istioctl` which will be download on cr. You can changed by change by change the following content of the cr


```
istio_manual_injection:
    enabled: true
    version: '1.1.0-snapshot.6' # version when you enable the manual inject via istioctl (it will download from Istio Release)
```


[source,shell]
----
make deploy-bookinfo-manual-sidecar
----

or with the following command for openshift:

[source,shell]
----
oc create -f operator/kiali-test-mesh-operator/deploy/cr/manual-sidecar/bookinfo-cr.yaml
----

or with the following command for kubernetes:

[source,shell]
----
kubectl create -f operator/kiali-test-mesh-operator/deploy/cr/manual-sidecar/bookinfo-cr.yaml
----

== Kiali Complex Test Mesh
After installing the <<Kiali Test Mesh Operator>>, you may install Kiali Complex Mesh which is a different type of mesh than the others. This mesh does not take any parameters and is not configurable.

This mesh includes mixing different configuration options. It spans multiple namespaces, uses deployments and replicasets, and apps and workloads. It is meant as a testing mesh to see how Kiali handles more complex scenarios.

=== Automatic Injection of sidecar
If you want to deploy with link:https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection[automatic injection of the sidecar] use the make target to deploy on openshift:


[source,shell]
----
deploy-complex-mesh-automatic-sidecar
----

or with the following command for openshift

[source,shell]
----
oc create -f operator/kiali-test-mesh-operator/deploy/cr/automatic-sidecar/complex_mesh-cr.yaml
----

or with the following command for kubernetes

[source,shell]
----
kubectl create -f operator/kiali-test-mesh-operator/deploy/cr/automatic-sidecar/complex_mesh-cr.yaml
----

=== Manual Injection of the Istio sidecar
In order to deploy with link:https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#manual-sidecar-injection[manual injection of sidecar] you can use the make target to deploy on openshift

[NOTE]
Check the version which of `istioctl` which will be download on cr. You can changed by change by change the following content of the cr


```
istio_manual_injection:
    enabled: true
    version: '1.1.0-snapshot.6' # version when you enable the manual inject via istioctl (it will download from Istio Release)
```


[source,shell]
----
deploy-complex-mesh-manual-sidecar
----

or with the following command for openshift:

[source,shell]
----
oc create -f operator/kiali-test-mesh-operator/deploy/cr/manual-sidecar/complex_mesh-cr.yaml
----

or with the following command for kubernetes:

[source,shell]
----
kubectl create -f operator/kiali-test-mesh-operator/deploy/cr/manual-sidecar/complex_mesh-cr.yaml
----
