= Kiali Test Mesh Operator

Kiali Test Mesmh provides an operator which will install different types of examples mesh which allow you to see different features of kiali.

In order to Deploy the Operator you can use following make target (on root folder of this repository)

[source,shell]
----
make deploy-operator
----

After installing the operator you can install the custom resource for each type of mesh that might want to try.

Meshes available:

- link:https://preliminary.istio.io/docs/examples/bookinfo/[Bookinfo]
- Kiali Complex Mesh


== Bookinfo from Istio 

[NOTE]
If you want to remove the CR defined, just change the makefile target command to from deploy to remove. As an example: `make deploy-bookinfo-automatic-sidecar` can become `make remove-bookinfo-automatic-sidecar`. 

If you want to use the openshift command just change from create to delete (eg: `oc create -f operator/kiali-test-mesh-operator/deploy/cr/automatic-sidecar/bookinfo-cr.yaml` will become `oc delete -f operator/kiali-test-mesh-operator/deploy/cr/automatic-sidecar/bookinfo-cr.yaml`)


=== Automatic Injection of Istio sidecar

After installing the <<Kiali Test Mesh Operator>>, you may install link:https://preliminary.istio.io/docs/examples/bookinfo/[Bookinfo] from Istio Sample  can be easily installed as part of the operator. You can choose to deploy with link:https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection[automatic injection of the sidecar] make target to deploy on openshift:

[source,shell]
----
make deploy-bookinfo-automatic-sidecar
----

or with the following command for openshift

[source,shell]
----
oc create -f operator/kiali-test-mesh-operator/deploy/cr/automatic-sidecar/bookinfo-cr.yaml -n kiali-test-mesh-operator
----

== Pulling Proxy Init from a Private Registry

If you are pulling Istio from a private registry, you will need to add a secret in order to start your mesh. Openshift does provide the option by linking a secret to a service account using the command `oc secrets link robot my-pull-secret --for=pull` where my-pull-secret is a secret for your pirvate registry.
Make sure your namespace and secret is linked


=== Manual Injection of the Istio sidecar
In order to deploy with link:https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#manual-sidecar-injection[manual injection of sidecar] you can use the make target to deploy on openshift

[NOTE]
Check the version which of `istioctl` which will be download on cr. You can changed by change by change the following content of the cr


```
istio_manual_injection:
    enabled: true
    version: '1.1.8 # version when you enable the manual inject via istioctl (it will download from Istio Release)
```


[source,shell]
----
make deploy-bookinfo-manual-sidecar
----


== Kiali Complex Test Mesh
After installing the <<Kiali Test Mesh Operator>>, you may install Kiali Complex Mesh which is a different type of mesh than the others.

This mesh includes mixing different configuration options. It spans multiple namespaces, uses deployments and replicasets, and apps and workloads. It is meant as a testing mesh to see how Kiali handles more complex scenarios.

=== Automatic Injection of sidecar
If you want to deploy with link:https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection[automatic injection of the sidecar] use the make target to deploy on openshift:


[source,shell]
----
deploy-complex-mesh-automatic-sidecar
----

or with the following command for openshift
