FROM registry.access.redhat.com/ubi8/ubi:latest
LABEL maintainer="Kiali <kiali-dev@googlegroups.com>"
ARG TARGETARCH
ENV TRAFFIC_GEN_BIN_HOME=/home \
    PATH=$TRAFFIC_GEN_BIN_HOME:$PATH
COPY vegeta-${TARGETARCH} $TRAFFIC_GEN_BIN_HOME/vegeta
COPY traffic-generator.sh $TRAFFIC_GEN_BIN_HOME/
WORKDIR $TRAFFIC_GEN_BIN_HOME
CMD ($TRAFFIC_GEN_BIN_HOME/traffic-generator.sh)
