- name: Wait until all pods of {{ item.name }} are running
  k8s:
    definition:
      apiVersion: "{{ item.api_version }}"
      kind: "{{ item.deployment_type }}"
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
      spec:
        selector:
          matchLabels:
            app: "{{ item.app }}"
  register: status
  until: (status.result.status.number_ready is defined and status.result.status.number_ready == 1) or
        (status.result.status.numberReady is defined and status.result.status.numberReady == 1) 
  retries: 100
  delay: 10
