- name: Deploy {{ item.name }} with Sidecar
  shell: "oc process -f {{item.file}} -p NAME={{ item.name }} -p APP_NAME={{ item.app }} -p APP_VERSION={{ item.version }} | istioctl kube-inject -f - | oc  apply -n {{ item.namespace }} -f -"
  when: "item.app is defined and item.sidecar == true"

- name: Deploy {{ item.name }} without Sidecar
  shell: "oc process -f {{item.file}} -p NAME={{ item.name }} -p APP_NAME={{ item.app }} -p APP_VERSION={{ item.version }}  | oc  apply -n {{ item.namespace }} -f -"
  when: "item.app is defined and item.sidecar == false"

- name: Deploy {{ item.name }} without App
  shell: "oc process -f {{item.file}} -p NAME={{ item.name }} -p PROJECT_NAME={{ item.project_name }} -p BUILD_NUMBER={{ item.build_number }} | istioctl kube-inject -f - | oc  apply -n {{ item.namespace }} -f -"
  when: 'item.project_name is defined'
