- name: Deleting Namespace {{ item }}
  openshift_raw:
    api_version: v1
    kind: Project
    name: "{{ item }}"
    state: absent
  ignore_errors: true

- name: Create Namespace {{ item }}
  openshift_raw:
    api_version: v1
    kind: Project
    name: "{{ item }}"
    state: present
  register: projectStatus
  until: projectStatus.changed == true
  retries: 100
  delay: 20

- name: Grant Privileged Permission to Namespace {{ item }}
  shell: "oc adm policy add-scc-to-user privileged -z default -n {{item}}"
