= Kiali Test Mesh Operator

Kiali Test Mesh Operator, based on (operator)[https://github.com/operator-framework/operator-sdk] compile test meshes can help you learn features of Istio and Kiali

Available Meshes:

- Kiali Complex Mesh

- link:https://istio.io/docs/examples/bookinfo/[Bookinfo from Istio]


[NOTE]
All the Bookinfo Demo pods and services are installed in the "bookinfo" namespace by default. If you want to define a different namespace on custom resource


== How to deploy on Openshift

Create project with  `oc new-project kiali-test-mesh-operator`

You can use the make option to deploy on openshift `make operator-deploy-openshift` or you can use the commands:

`oc process -f operator/kiali-test-mesh-operator/deploy/openshift/operator.yaml | oc create -f -`


And deploy the custom resource definition

`oc create -f operator/kiali-test-mesh-operator/deploy/cr.yaml`



== How to deploy on Kubernetes

Create project with `kubectl create namespace kiali-test-mesh-operator`
You can use the make option to deploy on kubenetes `make operator-deploy-k8s` or you can use the comamnds:

``` 
kubectl create -f operator/kiali-test-mesh-operator/deploy/k8s/installation_crd.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/k8s/installation_crd.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/k8s/service_account.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/k8s/role_binding.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/k8s/operator.yaml
kubectl create -f operator/kiali-test-mesh-operator/deploy/cr.yaml
```



== Custom Resource Options

Minimum resource:

```
apiVersion: kiali-test-mesh.kiali.io/v1
kind: Installation
metadata:
  name: kiali-test-mesh-installation
```

Possible Options to add on Custom Resource




```
complex_mesh:
  enabled: true # Enabled by default


istio_manual_injection:
  enabled: false # Disabled by default
  version: '1.1.0-snapshot.6' # version when you enable the manua inject via istioctl (it will download from Istio Release)


bookinfo:
  enabled: true # enabled by default
  version: 1.10.0 # version of bookinfo
  namespace: bookinfo # standard default namespace for bookinfo
  mongodb: true # mongodb enabled by default
  mysql: true # mysql enabled by default
```
